language: node_js
node_js:
  - '0.10'

install:
  - npm install -g grunt-cli
  - npm install

script:
  - grunt petal-dist

deploy:
  provider: s3
  bucket: shakr-petal
  access_key_id:
    secure: "CF963lMj+iuhD7GETOfv7DcRb1nm2C/Z3V1SKTG8mCMe5ottxfHgnJMIfMlR8by1msyHfhjVcWTXppkx+offYsJ6hhYRZTuoF5/C6KpmYAT8alhnf+Z8fap2MMlrKHSFK94e9PazTxxw8yPGLY9apw6YQS4wHh4uJLch7gErsGW2xNJYSEeIbru/HPFKRWWPNXQ2NRzipJs5DDkRYRqTwzLsURvhaCQV6Eo6jVb5AdwnknKLoHk1oTzbUGKc7C5zp2L7z0mHPeIACiLdi8febAoEUFTkNca7NU3jq+GY4HWVsrK8ADyES4bEn/MrU8kUmLXsNzvW2AXEfYXyIPW+f/RMeSFHztF0JZipnmm5IdnQ6PtxuHkZC0ipwLCghxuZeS3sPqDzT8VmgZtvHd1658RGrl4K+Gjuu8rgB4ItYS0LC+pD2QxkubzBZDSOjGCjmdJrwt80u3R0iiUyC0ZMYfC1oK0GjC5psy+W6Pe//oEm+fFaMJpgMPIH5ovgmtZjUXOsTn2Q6K/DapCQ1gk1YmolGsB+Vg0zoTCZnkmnfXW/P1ypMNbXX/8zNXrxwbhGVy0ene6ylrBQ+k3LdgczB3NHl6mVxtMos+1zipK1qxk3KvQbOOMtmM28xY19Rqrh9gXEIXzcUA20FFnvTAvuwpBVyfwtQMBBhLMA38knx5E="
  secret_access_key:
    secure: "A1TKFGg7D4O5GJ1+kfgQwlLUpDmby5nyEdG1+g3NOXiCLpenfOAzAVtrk3EkVAjZd3cKAqdXrcnUUXewn8U8KBUY14kWSledh2HtcnixcSOAZg14qyPIeCIyGJMubOsBGFKw3ec4U5J+AcYPteN3zDdb6h+SKMDVGTVVjOZuujNimbtp5I0p8HWJzLCpEADZxemkxxpC9M6Ki5jY33oZeTqYenarpEPK3/JFZmLRidIk+xDzVh/yUPs6ke2Wyw4K65ryN01P4X9OKK9bFpQQS/RzCDRtdnogsxu9kAeYVGHwBH0Ewr0A4jTDbO0xrP/imKZcCIvyMsEUpWjzYzXCghbsy/7CKqhrWRGQJyOUlG+EMzRIuFSzOqjOPEBtP1VPO6Lp6SrGTEC5KzdzMRljpppwrlwx4hIUJr1OIRxrt4uIAaXGfGPsn5FUp04oyYxUy+1yB/2w729fCwlZQcVLUg3OiuEU3270PsF1rkpoRxMbRmai9VE1nOVnXH7Iw5TodwgXzUXhxytBJ1APinSt8y9bieXhxTVrY9L4/8ldQPpGnOZ8GHnl3ccjQeHe87v5Xr3/IAxtvVvgX8RjXkpmSSMZn1EG7AozXnNvL2dtWaGviAho/uyp2YEhtcGwiAor+6zBFPtBs1RyepgV5Lv+y9siasSmpv26VZAnEt2q9R0="
  skip_cleanup: true
  acl: public_read
  region: ap-northeast-1
  local_dir: _dist
  upload_dir: edge
